{"name": "test_added_cart_favorites", "status": "skipped", "statusDetails": {"message": "XFAIL После добавления товара в избранное он не отображается на вкладке \"Избранное\"\n\nselene.core.exceptions.TimeoutException: Message: \n\nTimed out after 10s, while waiting for:\nbrowser.element(('css selector', '[href=\"/pages/favorites\"]')).click\n\nReason: NoSuchElementException: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href=\"/pages/favorites\"]\"}\n  (Session info: chrome=122.0.6261.94); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nScreenshot: file://C:\\Users\\rusel\\.selene\\screenshots\\1715542900606\\1715542900606.png\nPageSource: file://C:\\Users\\rusel\\.selene\\screenshots\\1715542900606\\1715542900606.html", "trace": "fn = <selene.core.wait.Command object at 0x0000018FED6E3D40>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\wait.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\wait.py:61: in __call__\n    return self._fn(entity)\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\entity.py:525: in raw_click\n    element.locate().click()\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\entity.py:185: in locate\n    return self._locator()\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\locator.py:34: in __call__\n    return self._locate()\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\_browser.py:71: in <lambda>\n    Locator(f'{self}.element({by})', lambda: self.driver.find_element(*by)),\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000018FED70C890>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...\\\\n#16 0x55b1abd10683 \\\\u003Cunknown>\\\\n#17 0x55b1abd21044 \\\\u003Cunknown>\\\\n#18 0x7f1ab0a8aac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href=\"/pages/favorites\"]\"}\nE         (Session info: chrome=122.0.6261.94); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       #0 0x55b1abd21e93 <unknown>\nE       #1 0x55b1aba19ce6 <unknown>\nE       #2 0x55b1aba64e48 <unknown>\nE       #3 0x55b1aba64f01 <unknown>\nE       #4 0x55b1abaa83f4 <unknown>\nE       #5 0x55b1aba86edd <unknown>\nE       #6 0x55b1abaa5899 <unknown>\nE       #7 0x55b1aba86c53 <unknown>\nE       #8 0x55b1aba57db3 <unknown>\nE       #9 0x55b1aba5877e <unknown>\nE       #10 0x55b1abce77cb <unknown>\nE       #11 0x55b1abceb7e5 <unknown>\nE       #12 0x55b1abcd50e1 <unknown>\nE       #13 0x55b1abcec372 <unknown>\nE       #14 0x55b1abcb91bf <unknown>\nE       #15 0x55b1abd10488 <unknown>\nE       #16 0x55b1abd10683 <unknown>\nE       #17 0x55b1abd21044 <unknown>\nE       #18 0x7f1ab0a8aac3 <unknown>\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\n    @pytest.mark.xfail(reason='После добавления товара в избранное он не отображается на вкладке \"Избранное\"')\n    def test_added_cart_favorites():\n    \n        favorites_page.open()\n    \n        favorites_page.find_cart('Поясная сумка')\n        favorites_page.detail_item()\n        favorites_page.add_to_favorites()\n>       favorites_page.entrance_to_favorites()\n\ntests\\test_favorites.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nboroda_land_project_tests\\pages\\favorites_page.py:26: in entrance_to_favorites\n    browser.element('[href=\"/pages/favorites\"]').click()\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\entity.py:540: in click\n    self.wait.for_(\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\wait.py:150: in for_\n    return self._decorator(self)(logic)(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfn = <selene.core.wait.Command object at 0x0000018FED6E3D40>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=getattr(reason, \"msg\", str(reason)),\n                    )\n                    # TODO: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    # TODO: should we have an option to turn on stacktrace logging?\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    # if it's a normal function, it should have __qualname__,\n                    # then use it, otherwise use str(fn)\n                    fn_name = getattr(\n                        fn,\n                        '__qualname__',\n                        getattr(fn, '__str__', lambda: str(fn))(),\n                    )\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn_name}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 10s, while waiting for:\nE                   browser.element(('css selector', '[href=\"/pages/favorites\"]')).click\nE                   \nE                   Reason: NoSuchElementException: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href=\"/pages/favorites\"]\"}\nE                     (Session info: chrome=122.0.6261.94); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE                   Screenshot: file://C:\\Users\\rusel\\.selene\\screenshots\\1715542900606\\1715542900606.png\nE                   PageSource: file://C:\\Users\\rusel\\.selene\\screenshots\\1715542900606\\1715542900606.html\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\wait.py:148: TimeoutException"}, "steps": [{"name": "Открываем сайт", "status": "passed", "start": 1715542959941, "stop": 1715542961977}, {"name": "В поисковой строке вводим наименование нужного товара", "status": "passed", "start": 1715542961977, "stop": 1715542963994}, {"name": "Открываем карточку товара", "status": "passed", "start": 1715542963994, "stop": 1715542965298}, {"name": "Добавляем товар в избранное", "status": "passed", "start": 1715542965298, "stop": 1715542965896}, {"name": "Переходим на вкладку избранное", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 10s, while waiting for:\nbrowser.element(('css selector', '[href=\"/pages/favorites\"]')).click\n\nReason: NoSuchElementException: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[href=\"/pages/favorites\"]\"}\n  (Session info: chrome=122.0.6261.94); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nScreenshot: file://C:\\Users\\rusel\\.selene\\screenshots\\1715542900606\\1715542900606.png\nPageSource: file://C:\\Users\\rusel\\.selene\\screenshots\\1715542900606\\1715542900606.html\n\n", "trace": "  File \"C:\\Users\\rusel\\QA.GURU\\qa_guru_python_9_11_Selene_UI_project\\boroda_land_project_tests\\pages\\favorites_page.py\", line 26, in entrance_to_favorites\n    browser.element('[href=\"/pages/favorites\"]').click()\n  File \"C:\\Users\\rusel\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\entity.py\", line 540, in click\n    self.wait.for_(\n  File \"C:\\Users\\rusel\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\wait.py\", line 150, in for_\n    return self._decorator(self)(logic)(fn)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rusel\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selene\\core\\wait.py\", line 148, in logic\n    raise self._hook_failure(failure)\n"}, "start": 1715542965896, "stop": 1715542976620}], "start": 1715542959941, "stop": 1715542976679, "uuid": "b57df7a3-4f96-4d12-b9f3-0cf6f83f6bc6", "historyId": "2cff4fbe0d1ae6bd55b2e8502838f8cb", "testCaseId": "2cff4fbe0d1ae6bd55b2e8502838f8cb", "fullName": "tests.test_favorites#test_added_cart_favorites", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='После добавления товара в избранное он не отображается на вкладке \"Избранное\"')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_favorites"}, {"name": "host", "value": "LAPTOP-KJ0V928H"}, {"name": "thread", "value": "9904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_favorites"}]}